stages:
  - build
  - db
  - test
  - deploy

image: gitlab-registry.wittkopf.eu/olly/recom-inventory-system:latest

variables:
  POSTGRES_DB: inventar
  POSTGRES_USER: inventar
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  XDEBUG_MODE: coverage

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - vendor/

build:
  stage: build
  script:
    # Install Composer dependencies
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-plugins

    # Install Node dependencies
    - npm ci --cache .npm --prefer-offline --quiet

    # Copy over testing configuration
    - cp .env.gitlab .env
    - cp .env .env.testing
    # Generate an application key, re-cache.
    - php artisan key:generate
    - php artisan config:cache

    # Activate telescope
    - php artisan telescope:install

    # Run npm build
    - npm run devq
  artifacts:
    paths:
      - vendor/
      - .npm/
      - .env
      - public/
    expire_in: 1 days
    when: always


prepare_db:
  stage: db
  dependencies:
    - build
  services:
    - postgres:latest
  script:
    # Run database migrations
    - php artisan migrate
    # Run database seed
    - php artisan db:seed

test_db:
  stage: db
  dependencies:
    - build
  services:
    - postgres:latest
  script:
    - eval $(ssh-agent -s)
    - echo "$PK_dev_inventoryx_com" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

    # Copy DB
    - scp ivdev@inventoryx.com:/var/www/dev/testdb.sql .

    # Import DB
    - psql -h postgres -U $POSTGRES_USER $POSTGRES_DB < testdb.sql

    # Run database migrations
    - php artisan migrate
  when: manual

test:
  stage: test
  dependencies:
    - build
  services:
    - postgres:latest
  script:
    # Run database migrations
    - php artisan migrate
    # recreate cache
    - php artisan config:cache

    # run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never
    # run frontend tests
    - npm test
    # run artisan tests
    - php artisan test

    # dusk
    # - /chromedriver/chromedriver 2>&1 &
    # - sleep 5
    # - nohup php artisan serve &
    # - php artisan dusk

deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$PK_dev_inventoryx_com" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

    - ~/.composer/vendor/bin/envoy run deploy --cleanup --commit="$CI_COMMIT_SHA"
  environment:
    name: development
    url: https://dev.inventoryx.com
  when: manual
  only:
    - development
